package model;
// Generated 10-dic-2018 10:36:39 by Hibernate Tools 4.3.1



/**
 * Armak generated by hbm2java
 */
public class Armak  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String jatorria;
     private String deskribapena;
     private Integer urtea;

    public Armak() {
    }

    public Armak(String name, String jatorria, String deskribapena, Integer urtea) {
       this.name = name;
       this.jatorria = jatorria;
       this.deskribapena = deskribapena;
       this.urtea = urtea;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getJatorria() {
        return this.jatorria;
    }
    
    public void setJatorria(String jatorria) {
        this.jatorria = jatorria;
    }
    public String getDeskribapena() {
        return this.deskribapena;
    }
    
    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }
    public Integer getUrtea() {
        return this.urtea;
    }
    
    public void setUrtea(Integer urtea) {
        this.urtea = urtea;
    }




}


